version: '3.8'

services:
  app:
    build: .
  db:
    image: "postgres:latest"
    volumes:
       - ./internal/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=buyers
    ports:
      - "54321:5432" 
