version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./app:/app
      - ./data:/data
    ports:
      - "8080:8080"
  db:
    image: "postgres:14.2"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=buyers

volumes:
  app:
  data:
  db-data:
